### ISSUE TITLE
Imrpove Error struct

### ISSUE THREAD

**Issue by ehedbor** [ehedbor/vdflex#10]
# Task List

- [ ] Add error positions (i.e. line and column numbers)
- [ ] Add `Backtrace` support, maybe?
- [ ] Finalize enum variants... or convert to a struct.
- [ ] Categorize the general type of error (e.g. syntax? semantics? IO?)

# Motivation

The current `Error` struct is a barebones enum lacking in a lot of useful information. For instance, the struct doesn't have any way of storing *where* the error occurred, which can be quite annoying for big files. Also, the enum variants aren't fully decided on yet; there is even one variant called `ToDo` that needs to be replaced.

I suggest taking inspiration from [`serde_json`'s `Error` struct[(https://docs.rs/serde_json/latest/serde_json/struct.Error.html).
